#!/bin/sh

SNOPT=..
PROBLEM=$SNOPT/examples
SRCDIR=$SNOPT/src

ftnchek -array=2 $PROBLEM/sqmain.f  \
                 $SRCDIR/snblas.f   \
                 $SRCDIR/sqopt.f    \
                 $SRCDIR/snoptq.f   \
                 $SRCDIR/sq02lib.f  \
                 $SRCDIR/sn02lib.f  \
                 $SRCDIR/sn03prnt.f \
                 $SRCDIR/sn04wrap.f \
                 $SRCDIR/sn10mach.f \
                 $SRCDIR/sn12ampl.f \
                 $SRCDIR/sn17util.f \
                 $SRCDIR/sn20amat.f \
                 $SRCDIR/sn25bfac.f \
                 $SRCDIR/sn27lu.f   \
                 $SRCDIR/sn30spec.f \
                 $SRCDIR/sn37wrap.f \
                 $SRCDIR/sn40bfil.f \
                 $SRCDIR/sn50lp.f   \
                 $SRCDIR/sn55qp.f   \
                 $SRCDIR/sn56qncg.f \
                 $SRCDIR/sn57qopt.f \
                 $SRCDIR/sn65rmod.f

