#!/bin/sh

SNOPT=..
PROBLEM=$SNOPT/examples
SRCDIR=$SNOPT/src

ftnchek -array=2 $PROBLEM/snmemtesta.f \
                 $SRCDIR/snblas.f   \
                 $SRCDIR/snopta.f   \
                 $SRCDIR/sq02lib.f  \
                 $SRCDIR/sn02lib.f  \
                 $SRCDIR/sn03prnt.f \
                 $SRCDIR/sn04wrap.f \
                 $SRCDIR/sn05wrpa.f \
                 $SRCDIR/sn10mach.f \
                 $SRCDIR/sn12ampl.f \
                 $SRCDIR/sn17util.f \
                 $SRCDIR/sn20amat.f \
                 $SRCDIR/sn25bfac.f \
                 $SRCDIR/sn27lu.f   \
                 $SRCDIR/sn30spec.f \
                 $SRCDIR/sn37wrap.f \
                 $SRCDIR/sn40bfil.f \
                 $SRCDIR/sn50lp.f   \
                 $SRCDIR/sn55qp.f   \
                 $SRCDIR/sn56qncg.f \
                 $SRCDIR/sn57qopt.f \
                 $SRCDIR/sn60srch.f \
                 $SRCDIR/sn65rmod.f \
                 $SRCDIR/sn70nobj.f \
                 $SRCDIR/sn80ncon.f \
                 $SRCDIR/sn85hess.f \
                 $SRCDIR/sn87sopt.f \
                 $SRCDIR/sn90lmqn.f \
                 $SRCDIR/sn95fmqn.f
