#! /usr/bin/sh

if [ $# -lt 1 ] ; then
  echo "usage: $0 <SetName> <libdir> <OPT|DBG>"
  exit 1
fi

SETNAME=$1
LIBDIR=$2
OPTTYPE=$3
STATSDIR=$HOME/snopt/utils
BASEDIR=.

cat probs[1abcdefgij].out \
    hardprobsc.out        \
    hsparse.out           \
    opf.out               \
    opf-eq.out            \
    spring.out            \
    springi.out           \
    rowse.out             \
    maxi.out              \
    t1diet.out            \
    t2banana.out          \
    t3qp.out              \
    t4manne.out           \
    t5weapon.out          \
    t6wood.out            \
    t7etamacro.out        >  $SETNAME.out

\rm	fort.4 2> /dev/null

egrep '(Begin|BEGIN|EXIT --|No. of infea|No. of it|No. of maj|No. of call|constraint violn|e for solv|  Linear |Problem name)' $SETNAME.out  >  fort.4

$STATSDIR/stats_snopt.exe

mv fort.4	$SETNAME.inn 	2> /dev/null
mv fort.7	$SETNAME.tex	2> /dev/null
mv fort.8	$SETNAME.run	2> /dev/null
mv fort.9	$SETNAME.sum	2> /dev/null


case $OPTTYPE in
*DBG*)  cp  $SETNAME.tex $BASEDIR/DBG_$SETNAME.tex ;;
*OPT*)  cp  $SETNAME.tex $BASEDIR/OPT_$SETNAME.tex ;;
esac
