function A = A(q1,q2,q3,I1,I2,I3,M,l,r)
%A
%    A = A(Q1,Q2,Q3,I1,I2,I3,M,L,R)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Nov-2018 12:09:23

t2 = r.^2;
t3 = cos(q2);
t4 = cos(q3);
t5 = t3.^2;
t6 = sin(q3);
t7 = -M.*l.*r.*t3.*t6-M.*t2.*t4.*t5.*t6;
t8 = t4.^2;
t9 = M.*t2.*t5.*t8;
t10 = sin(q2);
t11 = M.*l.*r.*t10;
t12 = q2.*2.0;
t13 = sin(t12);
t14 = (M.*t2.*t4.*t13)./2.0;
t15 = t11+t14;
t16 = l.^2;
t17 = M.*t2.*t5;
A = reshape([-I1+t9-M.*t2,t7,t15,t7,-I2-t9+t17-M.*t2-M.*t16-M.*l.*r.*t3.*t4.*2.0,M.*t2.*t6.*t13.*(-1.0./2.0),t15,-M.*t2.*t3.*t6.*t10,-I3-t17-M.*t16-M.*l.*r.*t3.*t4.*2.0],[3,3]);
