function b = b(q1,q2,q3,u1,u2,u3,I1,I2,I3,M,l,r,g)
%B
%    B = B(Q1,Q2,Q3,U1,U2,U3,I1,I2,I3,M,L,R,G)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Nov-2018 12:09:23

t2 = sin(q2);
t3 = cos(q2);
t4 = l.^2;
t5 = sin(q3);
t6 = u2.^2;
t7 = u3.^2;
t8 = cos(q3);
b = [-I2.*u2.*u3+I3.*u2.*u3-M.*l.*r.*t2.*u1.*u2-M.*l.*r.*t3.*t5.*u1.*u3;I1.*u1.*u3-I3.*u1.*u3-M.*t4.*u1.*u3-M.*g.*l.*t2-M.*l.*r.*t2.*t6-M.*l.*r.*t2.*t7-M.*l.*r.*t3.*t8.*u1.*u3;-I1.*u1.*u2+I2.*u1.*u2+M.*t4.*u1.*u2-M.*g.*l.*t3.*t5-M.*l.*r.*t3.*t5.*t6-M.*l.*r.*t3.*t5.*t7+M.*l.*r.*t3.*t8.*u1.*u2];
