function b = b(q1,q2,q3,u1,u2,u3,I1,I2,I3,tau1,tau2,tau3,f1,f2,f3,M,l,r,g)
%B
%    B = B(Q1,Q2,Q3,U1,U2,U3,I1,I2,I3,TAU1,TAU2,TAU3,F1,F2,F3,M,L,R,G)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    24-Nov-2018 19:13:11

t2 = sin(q2);
t3 = cos(q2);
t4 = sin(q3);
t5 = cos(q3);
t6 = l.^2;
t7 = u2.^2;
t8 = u3.^2;
b = [-tau1-I2.*u2.*u3+I3.*u2.*u3+f2.*r.*t2+f3.*r.*t3.*t4-M.*l.*r.*t2.*u1.*u2-M.*l.*r.*t3.*t4.*u1.*u3;-tau2+f3.*l+I1.*u1.*u3-I3.*u1.*u3-f1.*r.*t2-M.*t6.*u1.*u3+f3.*r.*t3.*t5-M.*g.*l.*t2-M.*l.*r.*t2.*t7-M.*l.*r.*t2.*t8-M.*l.*r.*t3.*t5.*u1.*u3;-tau3-f2.*l-I1.*u1.*u2+I2.*u1.*u2+M.*t6.*u1.*u2-f1.*r.*t3.*t4-f2.*r.*t3.*t5-M.*g.*l.*t3.*t4-M.*l.*r.*t3.*t4.*t7-M.*l.*r.*t3.*t4.*t8+M.*l.*r.*t3.*t5.*u1.*u2];
