#!/bin/sh

if [ $# -lt 2 ] ; then
  echo "usage: $0 <problem_name> <lib_dir>                               "
  echo "where:                                                           "
  echo " <problem_name> is from:                                         "
  echo "     snchka                                                      "
  echo "     sntoya     sntoyb   snmaina   snmainb    snmainc npmain     "
  echo "    t1dieta    t1dietb t2bananaa t2bananab       t3qp            "
  echo "   t4mannea   t4manneb  t5weapon    t6wood t7etamacro            "
  echo " snmemtesta snmemtestb   catmixa   catmixb    catmixc tester     "
  echo "    calvara    springa   springb   springbi      maxi            "
  echo "    hsmaina     hs118     slmain    sqmain    sqmain2            "
  echo "  slmainMPS sqmainMPS                                            "
  echo " <lib_dir>  is the path to the load libraries                    "
  exit 1
fi

CURDIR=$PWD
PROBLEM=$1
LIBDIR=$2

if test ! -f  ./$PROBLEM
then
   echo "Error: \"$PROBLEM\" is an unrecognized problem."
   exit 1
fi

echo "                                     "
echo "Running executable: \"$PWD/$PROBLEM\""
echo "                                     "

SAVE_PATH=$LD_LIBRARY_PATH
LD_LIBRARY_PATH=$LIBDIR
export LD_LIBRARY_PATH
echo   LD_LIBRARY_PATH=$LD_LIBRARY_PATH

if test ! -f  $PROBLEM.spc
then
   echo "Error: No specs file  $PROBLEM.spc  found for \"$PROBLEM\"."
   exit 2
fi

# Execute the example
../libtool --mode=execute valgrind -v --tool=memcheck --leak-check=full --dsymutil=yes  ./$PROBLEM

LD_LIBRARY_PATH=$SAVE_PATH
export LD_LIBRARY_PATH
