/* confdefs.h */
#define PACKAGE_NAME "SNOPT"
#define PACKAGE_TARNAME "snopt"
#define PACKAGE_VERSION "7.6"
#define PACKAGE_STRING "SNOPT 7.6"
#define PACKAGE_BUGREPORT "optimizers@ccom.ucsd.edu"
#define PACKAGE_URL ""
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
